### ISSUE TITLE
Deploy a mock server for time-tracker-api

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-api#31]
UI team is working with hard-coded data for now since we don't have an API up and running. Since we have the OPEN API definition file, we can deploy a mock server simulating responses.
 
A good mock server implementation is prism (https://github.com/stoplightio/prism) which can be installed in a tiny server using the following instructions:
1. Instal prism `npm install -g @stoplight/prism-cli`
2. Run prim using the Open API specification file `prism mock your-swagger-file.json` 

**Acceptance Criteria**
- Talk to back-end team in order to have the latest swagger.json file
- Provide the prism output so all team can know what the URLs are
- The URL should be accessible by internet

**Comment by EliuX** [comment]
This is going to have a workaround. We are going to use persistence directly.
