### ISSUE TITLE
Remove technologies as domain entity

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-api#37]
We have defined technologies as a domain entity comprised of two fields. We analyzed the stack-exchange API and we have decided to read all the technologies available in that API to be used when users are creating new time-entry objects (check https://github.com/ioet/time-tracker-ui/issues/29). Taking this idea into account, we need to remove the technology domain object form the OpenApi specification and use a string array as part of technologies during the time-entry domain object creation.

**Acceptance Criteria**
- Remove the `technology` domain object from project
- Remove all the associated namespaces and other files
- Make sure the generated swagger file has no references to this removed domain object
- time-entry objects should be created using an array of strings instead of technology objects.
- Remove any other associated dependency if that exists

**Comment by ralden** [comment]
@enriquezrene In what sense is technologies no longer a "domain entity"? It sounds like you have changed the _implementation_ and maybe the stored _representation_. But technologies is still an important concept in the domain; one that will probably change again in the future. Seems like it really should be fully encapsulated.
